version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/cycles-protocol-service"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
