package io.runcycles.protocol.api.auth;

import com.fasterxml.jackson.databind.ObjectMapper;
import io.runcycles.protocol.data.exception.CyclesProtocolException;
import io.runcycles.protocol.data.service.ApiKeyValidationService;
import io.runcycles.protocol.model.Enums;
import io.runcycles.protocol.model.auth.ApiKeyValidationResponse;
import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Component;
import org.springframework.util.AntPathMatcher;
import org.springframework.web.filter.OncePerRequestFilter;

import java.io.IOException;
import java.time.Instant;
import java.util.Map;
import java.util.UUID;

@Component
public class ApiKeyAuthenticationFilter extends OncePerRequestFilter {

    private static final Logger LOG = LoggerFactory.getLogger(ApiKeyAuthenticationFilter.class);
    private static final AntPathMatcher PATH_MATCHER = new AntPathMatcher();
    @Autowired
    private ApiKeyValidationService apiKeyValidationService;
    @Autowired
    private ObjectMapper objectMapper;

    @Override
    protected void doFilterInternal(
            HttpServletRequest request,
            HttpServletResponse response,
            FilterChain filterChain)
            throws ServletException, IOException {

        String apiKey = request.getHeader("X-Cycles-API-Key");
        LOG.debug("Authorization filter: apiKey={}",
                apiKey != null && apiKey.length() > 8 ? apiKey.substring(0, 8) + "***" : "***");

        if (apiKey == null || apiKey.isBlank()) {
            LOG.error("Missing API key: path={}",request.getRequestURI());
            sendErrorResponse(request, response, "Missing API key");
            return;
        }
        ApiKeyValidationResponse result = apiKeyValidationService.isValid(apiKey);

        if (!result.isValid()) {
            LOG.error("API key validation failed: result={}",result);
            sendErrorResponse(request, response, result.getReason());
            return;
        }

        ApiKeyAuthentication authentication =
                new ApiKeyAuthentication(
                        apiKey,
                        result.getTenantId(),
                        result.getKeyId(),
                        result.getPermissions());

        SecurityContextHolder.getContext().setAuthentication(authentication);

        // Set tenant header before the response is committed
        response.setHeader("X-Cycles-Tenant", result.getTenantId());

        filterChain.doFilter(request, response);
    }
    @Override
    protected boolean shouldNotFilter(HttpServletRequest request) {
        String path = request.getRequestURI();
        for (String pattern : SecurityConfig.PUBLIC_PATHS) {
            if (PATH_MATCHER.match(pattern, path)) {
                return true;
            }
        }
        return false;
    }
    private void sendErrorResponse(HttpServletRequest request, HttpServletResponse response, String reason) throws IOException {
        response.setStatus(HttpServletResponse.SC_UNAUTHORIZED);
        response.setContentType(MediaType.APPLICATION_JSON_VALUE);
        response.setCharacterEncoding("UTF-8");

        // Reuse the request ID generated by RequestIdFilter (runs before this filter)
        Object requestIdAttr = request.getAttribute(io.runcycles.protocol.api.filter.RequestIdFilter.REQUEST_ID_ATTRIBUTE);
        String requestId = requestIdAttr != null ? requestIdAttr.toString() : UUID.randomUUID().toString();

        Map<String, Object> body = Map.of(
                "error", Enums.ErrorCode.UNAUTHORIZED,
                "message", reason,
                "request_id", requestId
        );

        objectMapper.writeValue(response.getWriter(), body);
    }
}
